version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  php: bigcommerce/internal-php@volatile

jobs:
  tests-unit:
    parameters:
      php-version:
        type: string
        default: "8.0"
    executor:
      name: php/php
      php-version: << parameters.php-version >>
    steps:
      - ci/pre-setup
      - php/composer-install:
          composer_version: '--2'
      - php/unit-phpunit:
          configuration: 'phpunit.xml'

workflows:
  version: 2
  full:
    jobs:
      - tests-unit:
          matrix:
            parameters:
              php-version: [ "8.0" ]
